### ISSUE TITLE
RFC: Error messages

### ISSUE THREAD

**Issue by krzkaczor** [krzkaczor/earl#15]
Error messages should clearly point what went wrong and where. 

I think Jest does a pretty good job here and probably we can reuse some of the modules.

Ideas:
* excepts should be able to specify context (second arg in Chai)
* Use colors to easily spot differences while comparing objects etc but keep diff "copyable" back to code (chai for example formats objects without commas :wtf:)
* Error message can contain part of the original source with a matcher that failed (jest does it afaik). We already have know how to find original source code (for autofix feature).
* modify stack trace to cut off earls internal. The top stack should be the user's code.

**Comment by sz-piotr** [comment]
> excepts should be able to specify context (second arg in Chai)

Agreed

> Use colors to easily spot differences while comparing objects etc but keep diff "copyable" back to code (chai for example formats objects without commas :wtf:)

As it turns out chai does not do this stupid formatting, rather it is mocha. We need to somehow contain the formatting in the error message, but this can be tricky because of mocha indentation. And then we cut ourselves off for other test runners

> Error message can contain part of the original source with a matcher that failed (jest does it afaik). We already have know how to find original source code (for autofix feature).

From my experience this doesn't work as well in jest (this might be the fault of my super hacky react native config). We could however print `expect(<value>).<matcher>(<expected>)` and if any of the values is too big we can control this during preety printing.

> modify stack trace to cut off earls internal. The top stack should be the user's code.
Don't do this. The eaiest solution is to always throw in the matcher instead of somewhere deep in the matcher.
