### ISSUE TITLE
Using chai libraries to save work

### ISSUE THREAD

**Issue by keithamus** [krzkaczor/earl#38]
Hey! I’m the current lead maintainer of chai, a friend linked me this project, looks cool!

We’ve been slowly extracting useful parts of chai out into separate modules which we hope will help other libraries (like this one) and also help to make chai better.

I noticed you have a couple of open issues around things like a plugin system, and better error messaging, I also notice you’re missing some assertions like deepEqual.

The libraries we’ve extracted so far:

 - deep-equal (https://github.com/chaijs/deep-eql) - used for `.deep.equal()`

 - type-detect (https://github.com/chaijs/type-detect) - used for chais `.to.be.a()` style assertions

 - loupe (https://github.com/chaijs/loupe) like nodes util.inspect, used for error messages

 - pathval (https://github.com/chaijs/pathval) which converts strings to property lookups, used in the `.to.have.nested.property` style assertions 

 - plugin-use (https://github.com/chaijs/plugin-use) which we just released today aims to provide a plugin system which will be the basis of chai 5 which is undergoing a ground up rewrite to use ES modules and typescript. 

There’s a few more which have even more specific requirements, but I think some of these might be very beneficial to you. 

As an aside, if you feel like you want to contribute to chai, feel free to get in touch. It’s an old project and lots of people use it, so we can’t move as quickly as a new library without annoying/losing lots of existing users, but contributing back to chai means you can impact millions of users!

**Comment by krzkaczor** [comment]
Hey!
Thanks so much for getting in touch! I will for sure take a closer look at extracted chai's libs.

But I need to state that one of the goals of the project is to rethink decisions that were taken in Chai (and similiar libs) and see if we can come up with something better (lets hope at least!). That's why for example earl is `deepEq` by default, also we have custom approach to `to.be.a` style checks. And finally, everything is written in TS and we are 100% committed to type-safety which forces some design decisions.

That being said, thanks again for creating these packages. If we're not gonna use them, in the worst case we will get inspired by your code and test cases ;)

Best,
Kris
